#!/usr/bin/env bash

# Verify is rsync is installed
if ! command -v rsync &> /dev/null
then
    echo "Command rsync could not be found"
    echo "Please install rsync"
    exit
fi
echo "Command rsync found! :)"


# Working directory
#WDIR=$(pwd)
WDIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

echo $WDIR

# Create the folders
mkdir -p ${WDIR}/files # Equivalente to user home folder
mkdir -p ${WDIR}/files/.config # Create config folder
mkdir -p ${WDIR}/files/.config/qtile # Create qtile folder
mkdir -p ${WDIR}/files/.config/ranger # Create ranger folder
mkdir -p ${WDIR}/files/.config/kitty # Create kitty folder
mkdir -p ${WDIR}/files/.config/rofi # Create rofi folder
mkdir -p ${WDIR}/files/.config/nitrogen # Create nitrogen folder
mkdir -p ${WDIR}/files/.config/gtk-2.0 # Create gtk-2.0 folder
mkdir -p ${WDIR}/files/.config/gtk-3.0 # Create gtk-3.0 folder
mkdir -p ${WDIR}/files/.scripts # Create scrips folder
mkdir -p ${WDIR}/files/wallpapers # Create wallpapers folder
DIR_CONF="${WDIR}/files/.config/"
DIR_FILES="${WDIR}/files/"

# Backup .bashrc file
cp ${HOME}/.bashrc ${DIR_FILES}

# Backup scripts
rsync -avu --delete "${HOME}/.scripts" "${WDIR}/files/"

# Backup .xinitrc filr
cp ${HOME}/.xinitrc ${WDIR}/files/.xinitrc

# Backup Qtile configs
rsync -avu --delete "${HOME}/.config/qtile" "${WDIR}/files/.config/"

# Backup ranger configs
rsync -avu --delete "${HOME}/.config/ranger" "${WDIR}/files/.config/"

# Backup kitty configs
rsync -avu --delete "${HOME}/.config/kitty" "${WDIR}/files/.config/"

# Backup rofi configs
rsync -avu --delete "${HOME}/.config/rofi" "${WDIR}/files/.config/"

# Backup wallpapers
rsync -avu --delete "${HOME}/wallpapers" "${WDIR}/files/"

# Set nitrogen configs
echo "[xin_-1]" > ${WDIR}/files/.config/nitrogen/bg-saved.cfg
echo "file=${HOME}/wallpapers/among-trees.jpg" >> ${WDIR}/files/.config/nitrogen/bg-saved.cfg
echo "mode=3" >> ${WDIR}/files/.config/nitrogen/bg-saved.cfg
echo "bgcolor=#000000" >> ${WDIR}/files/.config/nitrogen/bg-saved.cfg

# Backup gtk configs
rsync -avu --delete "${HOME}/.config/gtk-2.0" "${WDIR}/files/.config/"
rsync -avu --delete "${HOME}/.config/gtk-3.0" "${WDIR}/files/.config/"


# Backup picom config
cp ${HOME}/.config/picom.conf ${WDIR}/files/.config
